export default {
  'Ahi': 'Fire',
  'Ao': 'Cloud',
  'Ara': 'Path',
  'Ariki': 'Chief, Priest or Leader',
  'Aroha': 'Love',
  'Ata': 'Shadow',
  'Atua': 'God, Demon, Supernatural Being',
  'Awa': 'River / Valley',
  'Awarua': 'Cloak',
  'Haere': 'Come / Go',
  'Hakari': 'Feast',
  'Hapu': 'Pregnant',
  'Hau': 'Wind',
  'Heke': 'Migrate',
  'Hiki': 'Charm',
  'Hinau': 'A tree',
  'Hua': 'Fruit / Egg',
  'Hui': 'Assembly',
  'Ika': 'Fish',
  'Iti': 'Small',
  'Iwi': 'Bones, Tribe',
  'Kai': 'Food',
  'Kaka': 'Parrot',
  'Kakahu': 'Cloak',
  'Kakapo': 'Ground Parrot',
  'Karaka': 'Poisonous Berry Tree',
  'Karakia': 'Charm / Spell',
  'Karanga': 'Call / Summon',
  'Kauri': 'Native Tree',
  'Kauru': 'Stem of ti-para',
  'Kea': 'Alpine Parrot',
  'Kereru': 'Wood Pigeon',
  'Kino': 'Bad',
  'Kiore': 'Native Rat',
  'Kiwi': 'Iconic Wingless Bird',
  'Koaro': 'Freshwater Fish',
  'Kohuru': 'Deal Treacherously',
  "Kokako": "North Island Crow",
  'Korere': "Feeding Funnel",
  'Korero': "Tell / Say / Discussion",
  'Kowhai': "Yellow",
  'Kumura': "Sweet Potato",
  'Kuri': "Dog",
  'Ma': "White / Clear",
  "Manga": "Stream",
  'Maire': "Native Tree",
  'Mako': "Shark",
  'Makomako': "Bellbird",
  'Makutu': "Bewitch",
  'Mana': "Authority / Psychic Force",
  'Manu': "Bird",
  'Manuka': "Tea Tree",
  'Marae': "True Home / Meeting Ground",
  'Mata': "Headland",
  'Mere': "Stone Club",
  'Miro': "Brown Pine",
  'Moa': "Large, Extinct Flightless Bird",
  'Moana': "Sea / Lake",
  'Mokihi': "Raft",
  'Morehu': "Survivors",
  'Motu': "Something Isolated",
  'Muri': "End",
  'Mutu': "Finished",
  'Niho': "Tooth",
  'Nikau': "New Zealand Palm",
  'Noa': "Free",
  'Nui': "Large / Great",
  'One': "Mud / Beach",
  'Pae': "Resting Place",
  'Pahu': "Gong",
  'Pai': "Excellent",
  'Pakihi': "Barren Land",
  'Papa': "Earth",
  'Patu': "Strike"
}
